### PR TITLE
Product page

### PR DESCRIPTION
**Pull request by VLeads**
Add Product page

Minor css fix

### CODE REVIEW

**Review by Anurag021 — APPROVED** [review]
code looks god to me

**Comment by Anurag021** [comment]
Product page is looking good, nice work, code also looks good to me.

**Comment by anik31** [comment]
Why have you used dismiss button in cards ? It is not required in product page.

**Comment by anik31** [comment]
image
There is space on right of the cards, you can align them to center or give gap between them.

**Comment by VLeads** [comment]
> image There is space on right of the cards, you can align them to center or give gap between them.

Thanks, I'll remove dismiss button and align spacing

**Pull request merged**
